### PR TITLE
Sirh 121 fe fetch filters from api to populate left side menu

### PR DESCRIPTION
**Pull request by atrincas**
### Overview

- Fetch filters from API
- Filter selection with FilterSelect component

### Feature relevant tickets

[SIRH-121](https://vizzuality.atlassian.net/browse/SIRH-121)

[SIRH-121]: https://vizzuality.atlassian.net/browse/SIRH-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by andresgnlez** [comment]
@atrincas 
image
 when I open the collapsed menu filter in the left side, a second scroll bar appears in the page. This happens, at least, on Chrome

**Comment by andresgnlez** [comment]
@atrincas 
image
Can we move the popover to the right side so it's not glued to the edge of the page?

**Comment by andresgnlez** [comment]
image
Nothing happens when I click on _Apply_ after selecting a couple of filters. I would expect the URL updated with the new filters and the widgets filtered by the new criteria.

**Comment by andresgnlez** [comment]
image
I would style the radio buttons with the same blue we are using for the checkboxes. 

image
Why is the last label blue and with quotation marks? Also, the triangle is blue while the rest of them are blackish.

**Comment by andresgnlez** [comment]
image

image

The list in general should "breath" more, with more verticales spaces and hover effects.

Design: https://www.figma.com/design/1MQAbB99h05eR5xbHqNDVn/4Growth-%5BInternal%5D?node-id=4506-86880&node-type=frame&t=oHlYY8eUHyPqHjGM-0

**Review by andresgnlez — CHANGES_REQUESTED** [review]
I left some comments.

**Comment by atrincas** [comment]
> Why is the last label blue and with quotation marks? Also, the triangle is blue while the rest of them are blackish.

It's according to what I saw in the figma Desin (Presentation tab)

**Comment by andresgnlez** [comment]
image
image

We have two different styles for the list, I don't think this is right.

**Comment by andresgnlez** [comment]
@atrincas take a look at the minor thing I mention above and feel free to merge after that.

**Review by andresgnlez — APPROVED** [review]

**Pull request merged**
